static COUNTRIES: [([u8; 2], &str); 249] = [
	([b'a', b'd'], "Andorra"),
	([b'a', b'e'], "United Arab Emirates"),
	([b'a', b'f'], "Afghanistan"),
	([b'a', b'g'], "Antigua and Barbuda"),
	([b'a', b'i'], "Anguilla"),
	([b'a', b'l'], "Albania"),
	([b'a', b'm'], "Armenia"),
	([b'a', b'o'], "Angola"),
	([b'a', b'q'], "Antarctica"),
	([b'a', b'r'], "Argentina"),
	([b'a', b's'], "American Samoa"),
	([b'a', b't'], "Austria"),
	([b'a', b'u'], "Australia"),
	([b'a', b'w'], "Aruba"),
	([b'a', b'x'], "Aland Islands"),
	([b'a', b'z'], "Azerbaijan"),
	([b'b', b'a'], "Bosnia and Herzegovina"),
	([b'b', b'b'], "Barbados"),
	([b'b', b'd'], "Bangladesh"),
	([b'b', b'e'], "Belgium"),
	([b'b', b'f'], "Burkina Faso"),
	([b'b', b'g'], "Bulgaria"),
	([b'b', b'h'], "Bahrain"),
	([b'b', b'i'], "Burundi"),
	([b'b', b'j'], "Benin"),
	([b'b', b'l'], "Saint Barthélemy"),
	([b'b', b'm'], "Bermuda"),
	([b'b', b'n'], "Brunei Darussalam"),
	([b'b', b'o'], "Bolivia"),
	([b'b', b'q'], "Bonaire"),
	([b'b', b'r'], "Brazil"),
	([b'b', b's'], "Bahamas"),
	([b'b', b't'], "Bhutan"),
	([b'b', b'v'], "Bouvet Island"),
	([b'b', b'w'], "Botswana"),
	([b'b', b'y'], "Belarus"),
	([b'b', b'z'], "Belize"),
	([b'c', b'a'], "Canada"),
	([b'c', b'c'], "Cocos (Keeling) Islands"),
	([b'c', b'd'], "Congo"),
	([b'c', b'f'], "Central African Republic"),
	([b'c', b'g'], "Congo"),
	([b'c', b'h'], "Switzerland"),
	([b'c', b'i'], "Cote d'Ivoire !"),
	([b'c', b'k'], "Cook Islands"),
	([b'c', b'l'], "Chile"),
	([b'c', b'm'], "Cameroon"),
	([b'c', b'n'], "China"),
	([b'c', b'o'], "Colombia"),
	([b'c', b'r'], "Costa Rica"),
	([b'c', b'u'], "Cuba"),
	([b'c', b'v'], "Cabo Verde"),
	([b'c', b'w'], "Curaçao"),
	([b'c', b'x'], "Christmas Island"),
	([b'c', b'y'], "Cyprus"),
	([b'c', b'z'], "Czechia"),
	([b'd', b'e'], "Germany"),
	([b'd', b'j'], "Djibouti"),
	([b'd', b'k'], "Denmark"),
	([b'd', b'm'], "Dominica"),
	([b'd', b'o'], "Dominican Republic"),
	([b'd', b'z'], "Algeria"),
	([b'e', b'c'], "Ecuador"),
	([b'e', b'e'], "Estonia"),
	([b'e', b'g'], "Egypt"),
	([b'e', b'h'], "Western Sahara"),
	([b'e', b'r'], "Eritrea"),
	([b'e', b's'], "Spain"),
	([b'e', b't'], "Ethiopia"),
	([b'f', b'i'], "Finland"),
	([b'f', b'j'], "Fiji"),
	([b'f', b'k'], "Falkland Islands (Malvinas)"),
	([b'f', b'm'], "Micronesia"),
	([b'f', b'o'], "Faroe Islands"),
	([b'f', b'r'], "France"),
	([b'g', b'a'], "Gabon"),
	([b'g', b'b'], "United Kingdom"),
	([b'g', b'd'], "Grenada"),
	([b'g', b'e'], "Georgia"),
	([b'g', b'f'], "French Guiana"),
	([b'g', b'g'], "Guernsey"),
	([b'g', b'h'], "Ghana"),
	([b'g', b'i'], "Gibraltar"),
	([b'g', b'l'], "Greenland"),
	([b'g', b'm'], "Gambia"),
	([b'g', b'n'], "Guinea"),
	([b'g', b'p'], "Guadeloupe"),
	([b'g', b'q'], "Equatorial Guinea"),
	([b'g', b'r'], "Greece"),
	([b'g', b's'], "South Georgia and the South Sandwich Islands"),
	([b'g', b't'], "Guatemala"),
	([b'g', b'u'], "Guam"),
	([b'g', b'w'], "Guinea-Bissau"),
	([b'g', b'y'], "Guyana"),
	([b'h', b'k'], "Hong Kong"),
	([b'h', b'm'], "Heard Island and McDonald Islands"),
	([b'h', b'n'], "Honduras"),
	([b'h', b'r'], "Croatia"),
	([b'h', b't'], "Haiti"),
	([b'h', b'u'], "Hungary"),
	([b'i', b'd'], "Indonesia"),
	([b'i', b'e'], "Ireland"),
	([b'i', b'l'], "Israel"),
	([b'i', b'm'], "Isle of Man"),
	([b'i', b'n'], "India"),
	([b'i', b'o'], "British Indian Ocean Territory"),
	([b'i', b'q'], "Iraq"),
	([b'i', b'r'], "Iran"),
	([b'i', b's'], "Iceland"),
	([b'i', b't'], "Italy"),
	([b'j', b'e'], "Jersey"),
	([b'j', b'm'], "Jamaica"),
	([b'j', b'o'], "Jordan"),
	([b'j', b'p'], "Japan"),
	([b'k', b'e'], "Kenya"),
	([b'k', b'g'], "Kyrgyzstan"),
	([b'k', b'h'], "Cambodia"),
	([b'k', b'i'], "Kiribati"),
	([b'k', b'm'], "Comoros"),
	([b'k', b'n'], "Saint Kitts and Nevis"),
	([b'k', b'p'], "Democratic People's Republic of Korea"),
	([b'k', b'r'], "Republic of Korea"),
	([b'k', b'w'], "Kuwait"),
	([b'k', b'y'], "Cayman Islands"),
	([b'k', b'z'], "Kazakhstan"),
	([b'l', b'a'], "Lao People's Democratic Republic"),
	([b'l', b'b'], "Lebanon"),
	([b'l', b'c'], "Saint Lucia"),
	([b'l', b'i'], "Liechtenstein"),
	([b'l', b'k'], "Sri Lanka"),
	([b'l', b'r'], "Liberia"),
	([b'l', b's'], "Lesotho"),
	([b'l', b't'], "Lithuania"),
	([b'l', b'u'], "Luxembourg"),
	([b'l', b'v'], "Latvia"),
	([b'l', b'y'], "Libya"),
	([b'm', b'a'], "Morocco"),
	([b'm', b'c'], "Monaco"),
	([b'm', b'd'], "Moldova"),
	([b'm', b'e'], "Montenegro"),
	([b'm', b'f'], "Saint Martin (French part)"),
	([b'm', b'g'], "Madagascar"),
	([b'm', b'h'], "Marshall Islands"),
	([b'm', b'k'], "Macedonia"),
	([b'm', b'l'], "Mali"),
	([b'm', b'm'], "Myanmar"),
	([b'm', b'n'], "Mongolia"),
	([b'm', b'o'], "Macao"),
	([b'm', b'p'], "Northern Mariana Islands"),
	([b'm', b'q'], "Martinique"),
	([b'm', b'r'], "Mauritania"),
	([b'm', b's'], "Montserrat"),
	([b'm', b't'], "Malta"),
	([b'm', b'u'], "Mauritius"),
	([b'm', b'v'], "Maldives"),
	([b'm', b'w'], "Malawi"),
	([b'm', b'x'], "Mexico"),
	([b'm', b'y'], "Malaysia"),
	([b'm', b'z'], "Mozambique"),
	([b'n', b'a'], "Namibia"),
	([b'n', b'c'], "New Caledonia"),
	([b'n', b'e'], "Niger"),
	([b'n', b'f'], "Norfolk Island"),
	([b'n', b'g'], "Nigeria"),
	([b'n', b'i'], "Nicaragua"),
	([b'n', b'l'], "Netherlands"),
	([b'n', b'o'], "Norway"),
	([b'n', b'p'], "Nepal"),
	([b'n', b'r'], "Nauru"),
	([b'n', b'u'], "Niue"),
	([b'n', b'z'], "New Zealand"),
	([b'o', b'm'], "Oman"),
	([b'p', b'a'], "Panama"),
	([b'p', b'e'], "Peru"),
	([b'p', b'f'], "French Polynesia"),
	([b'p', b'g'], "Papua New Guinea"),
	([b'p', b'h'], "Philippines"),
	([b'p', b'k'], "Pakistan"),
	([b'p', b'l'], "Poland"),
	([b'p', b'm'], "Saint Pierre and Miquelon"),
	([b'p', b'n'], "Pitcairn"),
	([b'p', b'r'], "Puerto Rico"),
	([b'p', b's'], "Palestine"),
	([b'p', b't'], "Portugal"),
	([b'p', b'w'], "Palau"),
	([b'p', b'y'], "Paraguay"),
	([b'q', b'a'], "Qatar"),
	([b'r', b'e'], "Reunion !"),
	([b'r', b'o'], "Romania"),
	([b'r', b's'], "Serbia"),
	([b'r', b'u'], "Russian Federation"),
	([b'r', b'w'], "Rwanda"),
	([b's', b'a'], "Saudi Arabia"),
	([b's', b'b'], "Solomon Islands"),
	([b's', b'c'], "Seychelles"),
	([b's', b'd'], "Sudan"),
	([b's', b'e'], "Sweden"),
	([b's', b'g'], "Singapore"),
	([b's', b'h'], "Saint Helena"),
	([b's', b'i'], "Slovenia"),
	([b's', b'j'], "Svalbard and Jan Mayen"),
	([b's', b'k'], "Slovakia"),
	([b's', b'l'], "Sierra Leone"),
	([b's', b'm'], "San Marino"),
	([b's', b'n'], "Senegal"),
	([b's', b'o'], "Somalia"),
	([b's', b'r'], "Suriname"),
	([b's', b's'], "South Sudan"),
	([b's', b't'], "Sao Tome and Principe"),
	([b's', b'v'], "El Salvador"),
	([b's', b'x'], "Sint Maarten (Dutch part)"),
	([b's', b'y'], "Syrian Arab Republic"),
	([b's', b'z'], "Swaziland"),
	([b't', b'c'], "Turks and Caicos Islands"),
	([b't', b'd'], "Chad"),
	([b't', b'f'], "French Southern Territories"),
	([b't', b'g'], "Togo"),
	([b't', b'h'], "Thailand"),
	([b't', b'j'], "Tajikistan"),
	([b't', b'k'], "Tokelau"),
	([b't', b'l'], "Timor-Leste"),
	([b't', b'm'], "Turkmenistan"),
	([b't', b'n'], "Tunisia"),
	([b't', b'o'], "Tonga"),
	([b't', b'r'], "Turkey"),
	([b't', b't'], "Trinidad and Tobago"),
	([b't', b'v'], "Tuvalu"),
	([b't', b'w'], "Taiwan"),
	([b't', b'z'], "Tanzania"),
	([b'u', b'a'], "Ukraine"),
	([b'u', b'g'], "Uganda"),
	([b'u', b'm'], "United States Minor Outlying Islands"),
	([b'u', b's'], "United States of America"),
	([b'u', b'y'], "Uruguay"),
	([b'u', b'z'], "Uzbekistan"),
	([b'v', b'a'], "Holy See"),
	([b'v', b'c'], "Saint Vincent and the Grenadines"),
	([b'v', b'e'], "Venezuela"),
	([b'v', b'g'], "British Virgin Islands"),
	([b'v', b'i'], "U.S. Virgin Islands"),
	([b'v', b'n'], "Viet Nam"),
	([b'v', b'u'], "Vanuatu"),
	([b'w', b'f'], "Wallis and Futuna"),
	([b'w', b's'], "Samoa"),
	([b'y', b'e'], "Yemen"),
	([b'y', b't'], "Mayotte"),
	([b'z', b'a'], "South Africa"),
	([b'z', b'm'], "Zambia"),
	([b'z', b'w'], "Zimbabwe"),
];

// Get country name by ISO 3166 lowercase alpha-2 code
pub fn get_name(code: &str) -> Option<&'static str> {
	if code.len() != 2 {
		return None;
	}

	let arr = unsafe {
		[
			*code.as_bytes().get_unchecked(0),
			*code.as_bytes().get_unchecked(1),
		]
	};
	let mut left = 0;
	let mut right = COUNTRIES.len() - 1;
	while left <= right {
		let mid = (left + right) / 2;
		let key = COUNTRIES[mid].0;
		if arr < key {
			right = mid - 1;
		} else if arr > key {
			left = mid + 1;
		} else {
			return Some(COUNTRIES[mid].1);
		}
	}
	None
}
