srcdir = '.'
blddir = '.build'
VERSION = '0.0.1'

def set_options(opt):
    opt.tool_options('compiler_cxx')

def configure(conf):
    conf.check_tool('compiler_cxx')
    conf.check_tool('node_addon')

def build(bld):
    obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
    obj.target = 'tripcode'
    obj.source = 'tripcode.cc'
    obj.env.append_value('LINKFLAGS', '-lcrypt') # uselib doesn't seem to work
    obj.env.append_value('LINKFLAGS', '-liconv')
