// Code generated by qtc from "board.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line board.html:1
package templates

//line board.html:1
import "strconv"

//line board.html:2
import "fmt"

//line board.html:3
import "github.com/bakape/meguca/config"

//line board.html:4
import "github.com/bakape/meguca/common"

//line board.html:5
import "github.com/bakape/meguca/lang"

//line board.html:6
import "github.com/bakape/meguca/imager/assets"

//line board.html:7
import ass "github.com/bakape/meguca/assets"

//line board.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line board.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line board.html:9
func streamrenderBoard(qw422016 *qt422016.Writer, threadHTML []byte, id, title string, conf config.BoardConfContainer, page, total int, pos common.ModerationLevel, catalog bool) {
//line board.html:10
	streamloadingImage(qw422016, conf.ID)
//line board.html:12
	ln := lang.Get()

//line board.html:13
	bannerID, mime, ok := ass.Banners.Random(conf.ID)

//line board.html:14
	if ok {
//line board.html:14
		qw422016.N().S(`<h1 class="image-banner">`)
//line board.html:16
		streamasset(qw422016, fmt.Sprintf("/assets/banners/%s/%d", conf.ID, bannerID), mime)
//line board.html:16
		qw422016.N().S(`</h1>`)
//line board.html:18
	}
//line board.html:18
	qw422016.N().S(`<h1 id="page-title">`)
//line board.html:20
	qw422016.N().S(title)
//line board.html:20
	qw422016.N().S(`</h1><span class="aside-container"><aside id="thread-form-container" class="glass"><span class="act"><a class="new-thread-button">`)
//line board.html:26
	qw422016.N().S(ln.Common.UI["newThread"])
//line board.html:26
	qw422016.N().S(`</a></span><form id="new-thread-form" action="/api/create-thread" method="post" enctype="multipart/form-data" class="hidden">`)
//line board.html:30
	if id == "all" {
//line board.html:30
		qw422016.N().S(`<select name="board" required>`)
//line board.html:32
		for _, b := range config.GetBoardTitles() {
//line board.html:33
			if b.ID == "all" {
//line board.html:34
				continue
//line board.html:35
			}
//line board.html:35
			qw422016.N().S(`<option value="`)
//line board.html:36
			qw422016.N().S(b.ID)
//line board.html:36
			qw422016.N().S(`">`)
//line board.html:37
			streamformatTitle(qw422016, b.ID, b.Title)
//line board.html:37
			qw422016.N().S(`</option>`)
//line board.html:39
		}
//line board.html:39
		qw422016.N().S(`</select><br>`)
//line board.html:42
	} else {
//line board.html:42
		qw422016.N().S(`<input type="text" name="board" value="`)
//line board.html:43
		qw422016.N().S(conf.ID)
//line board.html:43
		qw422016.N().S(`" hidden>`)
//line board.html:44
	}
//line board.html:44
	qw422016.N().S(`<input name="subject" placeholder="`)
//line board.html:45
	qw422016.N().S(ln.UI["subject"])
//line board.html:45
	qw422016.N().S(`" required type="text" maxlength="100"><br>`)
//line board.html:47
	streamnoscriptPostCreationFields(qw422016, pos)
//line board.html:48
	if id == "all" || !conf.TextOnly {
//line board.html:49
		streamuploadForm(qw422016)
//line board.html:50
	}
//line board.html:51
	streamcaptcha(qw422016, id)
//line board.html:52
	streamsubmit(qw422016, false)
//line board.html:52
	qw422016.N().S(`</form></aside><aside id="refresh" class="act glass noscript-hide"><a>`)
//line board.html:57
	qw422016.N().S(ln.Common.UI["refresh"])
//line board.html:57
	qw422016.N().S(`</a></aside>`)
//line board.html:60
	streamcatalogLink(qw422016, catalog)
//line board.html:61
	if !catalog {
//line board.html:62
		streampagination(qw422016, page, total)
//line board.html:63
	}
//line board.html:64
	streamhoverReveal(qw422016, "aside", conf.Notice, ln.Common.UI["showNotice"])
//line board.html:65
	streamhoverReveal(qw422016, "aside", conf.Rules, ln.Common.UI["rules"])
//line board.html:65
	qw422016.N().S(`<span id="catalog-controls" class="margin-spaced noscript-hide"><input type="text" name="search" placeholder="`)
//line board.html:67
	qw422016.N().S(ln.Common.UI["search"])
//line board.html:67
	qw422016.N().S(`" title="`)
//line board.html:67
	qw422016.N().S(ln.UI["searchTooltip"])
//line board.html:67
	qw422016.N().S(`">`)
//line board.html:68
	if catalog {
//line board.html:68
		qw422016.N().S(`<select name="sortMode">`)
//line board.html:70
		for i, s := range [...]string{"bump", "lastReply", "creation", "replyCount", "fileCount"} {
//line board.html:70
			qw422016.N().S(`<option value="`)
//line board.html:71
			qw422016.N().S(s)
//line board.html:71
			qw422016.N().S(`">`)
//line board.html:72
			qw422016.N().S(ln.SortModes[i])
//line board.html:72
			qw422016.N().S(`</option>`)
//line board.html:74
		}
//line board.html:74
		qw422016.N().S(`</select>`)
//line board.html:76
	}
//line board.html:76
	qw422016.N().S(`</span></span><hr>`)
//line board.html:80
	qw422016.N().Z(threadHTML)
//line board.html:80
	qw422016.N().S(`<script id="board-configs" type="application/json">`)
//line board.html:82
	qw422016.N().Z(conf.JSON)
//line board.html:82
	qw422016.N().S(`</script><hr><span class="aside-container">`)
//line board.html:86
	streamcatalogLink(qw422016, catalog)
//line board.html:87
	if !catalog {
//line board.html:88
		streampagination(qw422016, page, total)
//line board.html:89
	}
//line board.html:89
	qw422016.N().S(`</span>`)
//line board.html:91
}

//line board.html:91
func writerenderBoard(qq422016 qtio422016.Writer, threadHTML []byte, id, title string, conf config.BoardConfContainer, page, total int, pos common.ModerationLevel, catalog bool) {
//line board.html:91
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:91
	streamrenderBoard(qw422016, threadHTML, id, title, conf, page, total, pos, catalog)
//line board.html:91
	qt422016.ReleaseWriter(qw422016)
//line board.html:91
}

//line board.html:91
func renderBoard(threadHTML []byte, id, title string, conf config.BoardConfContainer, page, total int, pos common.ModerationLevel, catalog bool) string {
//line board.html:91
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:91
	writerenderBoard(qb422016, threadHTML, id, title, conf, page, total, pos, catalog)
//line board.html:91
	qs422016 := string(qb422016.B)
//line board.html:91
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:91
	return qs422016
//line board.html:91
}

// CatalogThreads renders thread content for a catalog page. Separate function to
// allow caching of generated posts.

//line board.html:95
func StreamCatalogThreads(qw422016 *qt422016.Writer, b []common.Thread, json []byte) {
//line board.html:95
	qw422016.N().S(`<div id="catalog">`)
//line board.html:97
	for _, t := range b {
//line board.html:98
		boardConfig := config.GetBoardConfigs(t.Board)

//line board.html:99
		idStr := strconv.FormatUint(t.ID, 10)

//line board.html:100
		hasImage := t.Image != nil && t.Image.ThumbType != common.NoFile

//line board.html:100
		qw422016.N().S(`<article id="p`)
//line board.html:101
		qw422016.N().S(idStr)
//line board.html:101
		qw422016.N().S(`"`)
//line board.html:101
		qw422016.N().S(` `)
//line board.html:101
		streampostClass(qw422016, t.Post, t.ID)
//line board.html:101
		qw422016.N().S(` `)
//line board.html:101
		qw422016.N().S(`data-id="`)
//line board.html:101
		qw422016.N().S(idStr)
//line board.html:101
		qw422016.N().S(`">`)
//line board.html:102
		streamdeletedToggle(qw422016)
//line board.html:103
		if hasImage {
//line board.html:103
			qw422016.N().S(`<figure>`)
//line board.html:105
			img := *t.Image

//line board.html:105
			qw422016.N().S(`<a href="/`)
//line board.html:106
			qw422016.N().S(t.Board)
//line board.html:106
			qw422016.N().S(`/`)
//line board.html:106
			qw422016.N().S(idStr)
//line board.html:106
			qw422016.N().S(`">`)
//line board.html:107
			if img.Spoiler {
//line board.html:107
				qw422016.N().S(`<img src="/assets/spoil/default.jpg" width="150" height="150" class="catalog">`)
//line board.html:109
			} else {
//line board.html:109
				qw422016.N().S(`<img width="`)
//line board.html:110
				qw422016.N().S(strconv.FormatUint(uint64(img.Dims[2]), 10))
//line board.html:110
				qw422016.N().S(`" height="`)
//line board.html:110
				qw422016.N().S(strconv.FormatUint(uint64(img.Dims[3]), 10))
//line board.html:110
				qw422016.N().S(`" class="catalog" src="`)
//line board.html:110
				qw422016.N().S(assets.ThumbPath(img.ThumbType, img.SHA1))
//line board.html:110
				qw422016.N().S(`">`)
//line board.html:111
			}
//line board.html:111
			qw422016.N().S(`</a></figure>`)
//line board.html:114
		}
//line board.html:114
		qw422016.N().S(`<span class="spaced thread-links hide-empty"><b class="board">/`)
//line board.html:117
		qw422016.N().S(t.Board)
//line board.html:117
		qw422016.N().S(`/</b><span class="counters">`)
//line board.html:120
		qw422016.N().S(strconv.FormatUint(uint64(t.PostCount), 10))
//line board.html:120
		qw422016.N().S(`/`)
//line board.html:122
		qw422016.N().S(strconv.FormatUint(uint64(t.ImageCount), 10))
//line board.html:122
		qw422016.N().S(`</span>`)
//line board.html:124
		if !hasImage {
//line board.html:125
			streamexpandLink(qw422016, t.Board, idStr)
//line board.html:126
		}
//line board.html:127
		streamlast100Link(qw422016, t.Board, idStr)
//line board.html:128
		streamthreadWatcherToggle(qw422016, t.ID)
//line board.html:128
		qw422016.N().S(`</span><br><h3>「`)
//line board.html:132
		qw422016.E().S(t.Subject)
//line board.html:132
		qw422016.N().S(`」</h3><blockquote>`)
//line board.html:135
		streambody(qw422016, t.Post, t.ID, t.Board, false, boardConfig.RbText, boardConfig.Pyu)
//line board.html:135
		qw422016.N().S(`</blockquote></article>`)
//line board.html:138
	}
//line board.html:138
	qw422016.N().S(`<script id="post-data" type="application/json">`)
//line board.html:140
	qw422016.N().Z(json)
//line board.html:140
	qw422016.N().S(`</script></div>`)
//line board.html:143
}

//line board.html:143
func WriteCatalogThreads(qq422016 qtio422016.Writer, b []common.Thread, json []byte) {
//line board.html:143
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:143
	StreamCatalogThreads(qw422016, b, json)
//line board.html:143
	qt422016.ReleaseWriter(qw422016)
//line board.html:143
}

//line board.html:143
func CatalogThreads(b []common.Thread, json []byte) string {
//line board.html:143
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:143
	WriteCatalogThreads(qb422016, b, json)
//line board.html:143
	qs422016 := string(qb422016.B)
//line board.html:143
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:143
	return qs422016
//line board.html:143
}

// IndexThreads renders abbreviated threads for display on board index pages

//line board.html:146
func StreamIndexThreads(qw422016 *qt422016.Writer, threads []common.Thread, json []byte) {
//line board.html:147
	root := config.Get().RootURL

//line board.html:148
	bls := extractBacklinks(15*6, threads...)

//line board.html:148
	qw422016.N().S(`<div id="index-thread-container">`)
//line board.html:150
	for _, t := range threads {
//line board.html:151
		idStr := strconv.FormatUint(t.ID, 10)

//line board.html:151
		qw422016.N().S(`<section class="index-thread`)
//line board.html:152
		if t.IsDeleted() {
//line board.html:152
			qw422016.N().S(` `)
//line board.html:152
			qw422016.N().S(`deleted`)
//line board.html:152
		}
//line board.html:152
		qw422016.N().S(`" data-id="`)
//line board.html:152
		qw422016.N().S(idStr)
//line board.html:152
		qw422016.N().S(`">`)
//line board.html:153
		streamdeletedToggle(qw422016)
//line board.html:154
		streamrenderThreadPosts(qw422016, t, bls, root, true)
//line board.html:154
		qw422016.N().S(`<hr></section>`)
//line board.html:157
	}
//line board.html:157
	qw422016.N().S(`<script id="post-data" type="application/json">`)
//line board.html:159
	qw422016.N().Z(json)
//line board.html:159
	qw422016.N().S(`</script>`)
//line board.html:161
	streamencodeBacklinks(qw422016, bls)
//line board.html:161
	qw422016.N().S(`</div>`)
//line board.html:163
}

//line board.html:163
func WriteIndexThreads(qq422016 qtio422016.Writer, threads []common.Thread, json []byte) {
//line board.html:163
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:163
	StreamIndexThreads(qw422016, threads, json)
//line board.html:163
	qt422016.ReleaseWriter(qw422016)
//line board.html:163
}

//line board.html:163
func IndexThreads(threads []common.Thread, json []byte) string {
//line board.html:163
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:163
	WriteIndexThreads(qb422016, threads, json)
//line board.html:163
	qs422016 := string(qb422016.B)
//line board.html:163
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:163
	return qs422016
//line board.html:163
}

// Render noscript-specific post creation fields

//line board.html:166
func streamnoscriptPostCreationFields(qw422016 *qt422016.Writer, pos common.ModerationLevel) {
//line board.html:167
	ln := lang.Get()

//line board.html:168
	if pos > common.NotStaff {
//line board.html:169
		streaminput(qw422016, staffTitleSpec.wrap(), ln)
//line board.html:170
	}
//line board.html:171
	for _, s := range specs["noscriptPostCreation"] {
//line board.html:172
		streaminput(qw422016, s, ln)
//line board.html:173
	}
//line board.html:174
}

//line board.html:174
func writenoscriptPostCreationFields(qq422016 qtio422016.Writer, pos common.ModerationLevel) {
//line board.html:174
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:174
	streamnoscriptPostCreationFields(qw422016, pos)
//line board.html:174
	qt422016.ReleaseWriter(qw422016)
//line board.html:174
}

//line board.html:174
func noscriptPostCreationFields(pos common.ModerationLevel) string {
//line board.html:174
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:174
	writenoscriptPostCreationFields(qb422016, pos)
//line board.html:174
	qs422016 := string(qb422016.B)
//line board.html:174
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:174
	return qs422016
//line board.html:174
}

// Render image upload form

//line board.html:177
func streamuploadForm(qw422016 *qt422016.Writer) {
//line board.html:177
	qw422016.N().S(`<span class="upload-container"><span data-id="spoiler"><label><input type="checkbox" name="spoiler">`)
//line board.html:182
	qw422016.N().S(lang.Get().Common.Posts["spoiler"])
//line board.html:182
	qw422016.N().S(`</label></span><span data-id="mask"><label title="`)
//line board.html:186
	qw422016.N().S(lang.Get().Common.Posts["maskTT"])
//line board.html:186
	qw422016.N().S(`"><input type="checkbox" name="mask">`)
//line board.html:188
	qw422016.N().S(lang.Get().Common.Posts["mask"])
//line board.html:188
	qw422016.N().S(`</label></span><br><input type="file" name="image" accept="image/png, image/gif, image/jpeg, video/webm, video/ogg, audio/ogg, application/ogg, video/mp4, audio/mp4, audio/mp3, application/zip, application/x-7z-compressed, application/x-xz, application/x-gzip, audio/x-flac, text/plain, application/pdf, video/quicktime, audio/x-flac"><br></span>`)
//line board.html:195
}

//line board.html:195
func writeuploadForm(qq422016 qtio422016.Writer) {
//line board.html:195
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:195
	streamuploadForm(qw422016)
//line board.html:195
	qt422016.ReleaseWriter(qw422016)
//line board.html:195
}

//line board.html:195
func uploadForm() string {
//line board.html:195
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:195
	writeuploadForm(qb422016)
//line board.html:195
	qs422016 := string(qb422016.B)
//line board.html:195
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:195
	return qs422016
//line board.html:195
}

// Link to catalog or board page

//line board.html:198
func streamcatalogLink(qw422016 *qt422016.Writer, catalog bool) {
//line board.html:199
	ln := lang.Get().Common.UI

//line board.html:199
	qw422016.N().S(`<aside class="act glass">`)
//line board.html:201
	if catalog {
//line board.html:201
		qw422016.N().S(`<a href=".">`)
//line board.html:203
		qw422016.N().S(ln["return"])
//line board.html:203
		qw422016.N().S(`</a>`)
//line board.html:205
	} else {
//line board.html:205
		qw422016.N().S(`<a href="catalog">`)
//line board.html:207
		qw422016.N().S(ln["catalog"])
//line board.html:207
		qw422016.N().S(`</a>`)
//line board.html:209
	}
//line board.html:209
	qw422016.N().S(`</aside>`)
//line board.html:211
}

//line board.html:211
func writecatalogLink(qq422016 qtio422016.Writer, catalog bool) {
//line board.html:211
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:211
	streamcatalogLink(qw422016, catalog)
//line board.html:211
	qt422016.ReleaseWriter(qw422016)
//line board.html:211
}

//line board.html:211
func catalogLink(catalog bool) string {
//line board.html:211
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:211
	writecatalogLink(qb422016, catalog)
//line board.html:211
	qs422016 := string(qb422016.B)
//line board.html:211
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:211
	return qs422016
//line board.html:211
}

// Links to different pages of the board index

//line board.html:214
func streampagination(qw422016 *qt422016.Writer, page, total int) {
//line board.html:214
	qw422016.N().S(`<aside class="glass spaced">`)
//line board.html:216
	if page != 0 {
//line board.html:217
		if page-1 != 0 {
//line board.html:218
			streampageLink(qw422016, 0, "<<")
//line board.html:219
		}
//line board.html:220
		streampageLink(qw422016, page-1, "<")
//line board.html:221
	}
//line board.html:222
	for i := 0; i < total; i++ {
//line board.html:223
		if i != page {
//line board.html:224
			streampageLink(qw422016, i, strconv.Itoa(i))
//line board.html:225
		} else {
//line board.html:225
			qw422016.N().S(`<b>`)
//line board.html:227
			qw422016.N().D(i)
//line board.html:227
			qw422016.N().S(`</b>`)
//line board.html:229
		}
//line board.html:230
	}
//line board.html:231
	if page != total-1 {
//line board.html:232
		streampageLink(qw422016, page+1, ">")
//line board.html:233
		if page+1 != total-1 {
//line board.html:234
			streampageLink(qw422016, total-1, ">>")
//line board.html:235
		}
//line board.html:236
	}
//line board.html:236
	qw422016.N().S(`</aside>`)
//line board.html:238
}

//line board.html:238
func writepagination(qq422016 qtio422016.Writer, page, total int) {
//line board.html:238
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:238
	streampagination(qw422016, page, total)
//line board.html:238
	qt422016.ReleaseWriter(qw422016)
//line board.html:238
}

//line board.html:238
func pagination(page, total int) string {
//line board.html:238
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:238
	writepagination(qb422016, page, total)
//line board.html:238
	qs422016 := string(qb422016.B)
//line board.html:238
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:238
	return qs422016
//line board.html:238
}

// Link to a different paginated board page

//line board.html:241
func streampageLink(qw422016 *qt422016.Writer, i int, text string) {
//line board.html:241
	qw422016.N().S(`<a href="?page=`)
//line board.html:242
	qw422016.N().D(i)
//line board.html:242
	qw422016.N().S(`">`)
//line board.html:243
	qw422016.N().S(text)
//line board.html:243
	qw422016.N().S(`</a>`)
//line board.html:245
}

//line board.html:245
func writepageLink(qq422016 qtio422016.Writer, i int, text string) {
//line board.html:245
	qw422016 := qt422016.AcquireWriter(qq422016)
//line board.html:245
	streampageLink(qw422016, i, text)
//line board.html:245
	qt422016.ReleaseWriter(qw422016)
//line board.html:245
}

//line board.html:245
func pageLink(i int, text string) string {
//line board.html:245
	qb422016 := qt422016.AcquireByteBuffer()
//line board.html:245
	writepageLink(qb422016, i, text)
//line board.html:245
	qs422016 := string(qb422016.B)
//line board.html:245
	qt422016.ReleaseByteBuffer(qb422016)
//line board.html:245
	return qs422016
//line board.html:245
}
