// This file is automatically generated by qtc from "board.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line board.qtpl:1
package templates

//line board.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line board.qtpl:1
import "strconv"

//line board.qtpl:2
import "github.com/bakape/meguca/config"

//line board.qtpl:3
import "github.com/bakape/meguca/common"

//line board.qtpl:4
import "github.com/bakape/meguca/lang"

//line board.qtpl:5
import "github.com/bakape/meguca/imager/assets"

//line board.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line board.qtpl:7
func streamrenderBoard(qw422016 *qt422016.Writer, threadHTML []byte, id, title string, conf config.BoardConfContainer, ln lang.Pack) {
	//line board.qtpl:13
	qw422016.N().S(`<h1 id="page-title">`)
	//line board.qtpl:15
	qw422016.N().S(title)
	//line board.qtpl:15
	qw422016.N().S(`</h1><span class="aside-container"><aside id="thread-form-container" class="glass"><span class="act"><a class="new-thread-button">`)
	//line board.qtpl:21
	qw422016.N().S(ln.UI["newThread"])
	//line board.qtpl:21
	qw422016.N().S(`</a></span><form id="new-thread-form" action="/createThread" class="hidden">`)
	//line board.qtpl:25
	if id == "all" {
		//line board.qtpl:25
		qw422016.N().S(`<select name="board" required>`)
		//line board.qtpl:27
		for _, b := range config.GetBoardTitles() {
			//line board.qtpl:27
			qw422016.N().S(`<option value="`)
			//line board.qtpl:28
			qw422016.N().S(b.ID)
			//line board.qtpl:28
			qw422016.N().S(`">`)
			//line board.qtpl:29
			streamformatTitle(qw422016, b.ID, b.Title)
			//line board.qtpl:29
			qw422016.N().S(`</option>`)
			//line board.qtpl:31
		}
		//line board.qtpl:31
		qw422016.N().S(`</select><br>`)
		//line board.qtpl:34
	}
	//line board.qtpl:34
	qw422016.N().S(`<input name="subject" placeholder="`)
	//line board.qtpl:35
	qw422016.N().S(ln.UI["subject"])
	//line board.qtpl:35
	qw422016.N().S(`" required type="text" maxlength="100"><br><noscript>`)
	//line board.qtpl:38
	for _, s := range specs["noscriptPostCreation"] {
		//line board.qtpl:39
		streaminput(qw422016, s, ln)
		//line board.qtpl:39
		qw422016.N().S(`<br>`)
		//line board.qtpl:41
	}
	//line board.qtpl:41
	qw422016.N().S(`</noscript>`)
	//line board.qtpl:43
	if id == "all" || !conf.TextOnly {
		//line board.qtpl:43
		qw422016.N().S(`<span class="upload-container"><span data-id="spoiler"><label><input type="checkbox" name="spoiler">`)
		//line board.qtpl:48
		qw422016.N().S(ln.Common.Posts["spoiler"])
		//line board.qtpl:48
		qw422016.N().S(`</label></span><strong class="upload-status"></strong><br><input type="file" name="image" accept="image/png, image/gif, image/jpeg, video/webm, video/ogg, audio/ogg, application/ogg, video/mp4, audio/mp4, audio/mp3, application/zip, application/x-7z-compressed, application/x-xz, application/x-gzip"><br></span>`)
		//line board.qtpl:56
	}
	//line board.qtpl:57
	streamcaptcha(qw422016, "new-thread", ln.UI)
	//line board.qtpl:57
	qw422016.N().S(`<input type="submit" value="`)
	//line board.qtpl:58
	qw422016.N().S(ln.UI["submit"])
	//line board.qtpl:58
	qw422016.N().S(`"><input type="button" name="cancel" value="`)
	//line board.qtpl:59
	qw422016.N().S(ln.UI["cancel"])
	//line board.qtpl:59
	qw422016.N().S(`"></form></aside><aside id="refresh" class="act glass"><a>`)
	//line board.qtpl:64
	qw422016.N().S(ln.Common.UI["refresh"])
	//line board.qtpl:64
	qw422016.N().S(`</a></aside>`)
	//line board.qtpl:67
	streamhoverReveal(qw422016, conf.Notice, ln.UI["showNotice"])
	//line board.qtpl:68
	streamhoverReveal(qw422016, conf.Rules, ln.UI["rules"])
	//line board.qtpl:68
	qw422016.N().S(`<span id="catalog-controls" class="margin-spaced"><input type="text" name="search" placeholder="`)
	//line board.qtpl:70
	qw422016.N().S(ln.UI["search"])
	//line board.qtpl:70
	qw422016.N().S(`" title="`)
	//line board.qtpl:70
	qw422016.N().S(ln.UI["searchTooltip"])
	//line board.qtpl:70
	qw422016.N().S(`"><select name="sortMode">`)
	//line board.qtpl:72
	for i, s := range [...]string{"lastReply", "creation", "replyCount", "fileCount"} {
		//line board.qtpl:72
		qw422016.N().S(`<option value="`)
		//line board.qtpl:73
		qw422016.N().S(s)
		//line board.qtpl:73
		qw422016.N().S(`">`)
		//line board.qtpl:74
		qw422016.N().S(ln.SortModes[i])
		//line board.qtpl:74
		qw422016.N().S(`</option>`)
		//line board.qtpl:76
	}
	//line board.qtpl:76
	qw422016.N().S(`</select></span></span><noscript>TODO: Noscript thread creation</noscript><hr><div id="catalog">`)
	//line board.qtpl:83
	qw422016.N().Z(threadHTML)
	//line board.qtpl:83
	qw422016.N().S(`<script id="board-configs" type="application/json">`)
	//line board.qtpl:85
	qw422016.N().Z(conf.JSON)
	//line board.qtpl:85
	qw422016.N().S(`</script></div><hr>`)
//line board.qtpl:89
}

//line board.qtpl:89
func writerenderBoard(qq422016 qtio422016.Writer, threadHTML []byte, id, title string, conf config.BoardConfContainer, ln lang.Pack) {
	//line board.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line board.qtpl:89
	streamrenderBoard(qw422016, threadHTML, id, title, conf, ln)
	//line board.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line board.qtpl:89
}

//line board.qtpl:89
func renderBoard(threadHTML []byte, id, title string, conf config.BoardConfContainer, ln lang.Pack) string {
	//line board.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
	//line board.qtpl:89
	writerenderBoard(qb422016, threadHTML, id, title, conf, ln)
	//line board.qtpl:89
	qs422016 := string(qb422016.B)
	//line board.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
	//line board.qtpl:89
	return qs422016
//line board.qtpl:89
}

// CatalogThreads renders thread content for a catalog page. Separate function to
// allow caching of generated posts.

//line board.qtpl:93
func StreamCatalogThreads(qw422016 *qt422016.Writer, b common.Board) {
	//line board.qtpl:94
	for _, t := range b {
		//line board.qtpl:95
		idStr := strconv.FormatUint(t.ID, 10)

		//line board.qtpl:96
		postCtr := strconv.FormatUint(uint64(t.PostCtr), 10)

		//line board.qtpl:97
		imgCtr := strconv.FormatUint(uint64(t.ImageCtr), 10)

		//line board.qtpl:97
		qw422016.N().S(`<article id="p`)
		//line board.qtpl:98
		qw422016.N().S(idStr)
		//line board.qtpl:98
		qw422016.N().S(`" class="glass" data-replyTime="`)
		//line board.qtpl:98
		qw422016.N().S(strconv.FormatInt(t.ReplyTime, 10))
		//line board.qtpl:98
		qw422016.N().S(`" data-time="`)
		//line board.qtpl:98
		qw422016.N().S(strconv.FormatInt(t.Time, 10))
		//line board.qtpl:98
		qw422016.N().S(`" data-postCtr="`)
		//line board.qtpl:98
		qw422016.N().S(postCtr)
		//line board.qtpl:98
		qw422016.N().S(`" data-imageCtr="`)
		//line board.qtpl:98
		qw422016.N().S(imgCtr)
		//line board.qtpl:98
		qw422016.N().S(`">`)
		//line board.qtpl:99
		if t.Image != nil {
			//line board.qtpl:99
			qw422016.N().S(`<figure>`)
			//line board.qtpl:101
			img := *t.Image

			//line board.qtpl:101
			qw422016.N().S(`<a class="history" href="/`)
			//line board.qtpl:102
			qw422016.N().S(t.Board)
			//line board.qtpl:102
			qw422016.N().S(`/`)
			//line board.qtpl:102
			qw422016.N().S(idStr)
			//line board.qtpl:102
			qw422016.N().S(`">`)
			//line board.qtpl:103
			if img.Spoiler {
				//line board.qtpl:103
				qw422016.N().S(`<img src="/assets/spoil/default.jpg" width="150" height="150" class="expanded">`)
				//line board.qtpl:105
			} else {
				//line board.qtpl:105
				qw422016.N().S(`<img width="`)
				//line board.qtpl:106
				qw422016.N().S(strconv.FormatUint(uint64(img.Dims[2]), 10))
				//line board.qtpl:106
				qw422016.N().S(`" height="`)
				//line board.qtpl:106
				qw422016.N().S(strconv.FormatUint(uint64(img.Dims[3]), 10))
				//line board.qtpl:106
				qw422016.N().S(`" class="expanded" src="`)
				//line board.qtpl:106
				qw422016.N().S(assets.ThumbPath(img.FileType, img.ThumbType, img.SHA1))
				//line board.qtpl:106
				qw422016.N().S(`">`)
				//line board.qtpl:107
			}
			//line board.qtpl:107
			qw422016.N().S(`</a></figure>`)
			//line board.qtpl:110
		}
		//line board.qtpl:110
		qw422016.N().S(`<span class="spaced thread-links"><b class="board">/`)
		//line board.qtpl:113
		qw422016.N().S(t.Board)
		//line board.qtpl:113
		qw422016.N().S(`/</b><span class="counters">`)
		//line board.qtpl:116
		qw422016.N().S(postCtr)
		//line board.qtpl:116
		qw422016.N().S(`/`)
		//line board.qtpl:116
		qw422016.N().S(imgCtr)
		//line board.qtpl:116
		qw422016.N().S(`</span>`)
		//line board.qtpl:118
		if t.Image == nil {
			//line board.qtpl:118
			qw422016.N().S(`<span class="act"><a class="history expand-link" href="/`)
			//line board.qtpl:120
			qw422016.N().S(t.Board)
			//line board.qtpl:120
			qw422016.N().S(`/`)
			//line board.qtpl:120
			qw422016.N().S(idStr)
			//line board.qtpl:120
			qw422016.N().S(`">Expand</a></span>`)
			//line board.qtpl:124
		}
		//line board.qtpl:124
		qw422016.N().S(`<span class="act"><a class="history lastN-link" href="/`)
		//line board.qtpl:126
		qw422016.N().S(t.Board)
		//line board.qtpl:126
		qw422016.N().S(`/`)
		//line board.qtpl:126
		qw422016.N().S(idStr)
		//line board.qtpl:126
		qw422016.N().S(`?last=100">Last 100</a></span></span><br><h3>「`)
		//line board.qtpl:133
		qw422016.E().S(t.Subject)
		//line board.qtpl:133
		qw422016.N().S(`」</h3></article>`)
		//line board.qtpl:136
	}
//line board.qtpl:137
}

//line board.qtpl:137
func WriteCatalogThreads(qq422016 qtio422016.Writer, b common.Board) {
	//line board.qtpl:137
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line board.qtpl:137
	StreamCatalogThreads(qw422016, b)
	//line board.qtpl:137
	qt422016.ReleaseWriter(qw422016)
//line board.qtpl:137
}

//line board.qtpl:137
func CatalogThreads(b common.Board) string {
	//line board.qtpl:137
	qb422016 := qt422016.AcquireByteBuffer()
	//line board.qtpl:137
	WriteCatalogThreads(qb422016, b)
	//line board.qtpl:137
	qs422016 := string(qb422016.B)
	//line board.qtpl:137
	qt422016.ReleaseByteBuffer(qb422016)
	//line board.qtpl:137
	return qs422016
//line board.qtpl:137
}

// Notice widget, that reveals text on hover

//line board.qtpl:140
func streamhoverReveal(qw422016 *qt422016.Writer, text, label string) {
	//line board.qtpl:141
	if text == "" {
		//line board.qtpl:142
		return
		//line board.qtpl:143
	}
	//line board.qtpl:143
	qw422016.N().S(`<aside class="glass hover-reveal"><span class="act">`)
	//line board.qtpl:146
	qw422016.N().S(label)
	//line board.qtpl:146
	qw422016.N().S(`</span><span class="popup-menu glass">`)
	//line board.qtpl:149
	qw422016.E().S(text)
	//line board.qtpl:149
	qw422016.N().S(`</span></aside>`)
//line board.qtpl:152
}

//line board.qtpl:152
func writehoverReveal(qq422016 qtio422016.Writer, text, label string) {
	//line board.qtpl:152
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line board.qtpl:152
	streamhoverReveal(qw422016, text, label)
	//line board.qtpl:152
	qt422016.ReleaseWriter(qw422016)
//line board.qtpl:152
}

//line board.qtpl:152
func hoverReveal(text, label string) string {
	//line board.qtpl:152
	qb422016 := qt422016.AcquireByteBuffer()
	//line board.qtpl:152
	writehoverReveal(qb422016, text, label)
	//line board.qtpl:152
	qs422016 := string(qb422016.B)
	//line board.qtpl:152
	qt422016.ReleaseByteBuffer(qb422016)
	//line board.qtpl:152
	return qs422016
//line board.qtpl:152
}
