// Code generated by qtc from "static.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line static.html:1
package templates

//line static.html:1
import "encoding/json"

//line static.html:2
import "github.com/bakape/meguca/lang"

// Boilerplate HTML for hover post previews on standalone pages

//line static.html:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line static.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line static.html:5
func StreamBoilerPlate(qw422016 *qt422016.Writer) {
//line static.html:6
	streamhtmlHeader(qw422016)
//line static.html:6
	qw422016.N().S(`<link rel="stylesheet" href="/assets/css/static.css">`)
//line static.html:8
	ln := lang.Get()

//line static.html:8
	qw422016.N().S(`<template name="article"><input type="checkbox" class="deleted-toggle"><header class="spaced"><b  class="name spaced"></b><img class="flag" hidden><time></time><nav><a>No.</a><a class="quote"></a></nav></header><div class="post-container"><blockquote></blockquote></div></template><template name="figcaption"><figcaption class="spaced"><span class="fileinfo"><span class="media-artist"></span><span class="media-title"></span><span hidden class="has-audio">♫</span><span class="media-length"></span><span class="filesize"></span><span class="dims"></span></span><a></a></figcaption></template><template name="figure"><figure><a><img></a></figure></template><script src="/assets/js/vendor/almond.js"></script><script id="lang-data" type="application/json">`)
//line static.html:48
	buf, _ := json.Marshal(ln.Common)

//line static.html:49
	qw422016.N().Z(buf)
//line static.html:49
	qw422016.N().S(`</script><script src="/assets/js/scripts/staticLoader.js"></script><body><div id="hover-overlay"></div>`)
//line static.html:54
}

//line static.html:54
func WriteBoilerPlate(qq422016 qtio422016.Writer) {
//line static.html:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line static.html:54
	StreamBoilerPlate(qw422016)
//line static.html:54
	qt422016.ReleaseWriter(qw422016)
//line static.html:54
}

//line static.html:54
func BoilerPlate() string {
//line static.html:54
	qb422016 := qt422016.AcquireByteBuffer()
//line static.html:54
	WriteBoilerPlate(qb422016)
//line static.html:54
	qs422016 := string(qb422016.B)
//line static.html:54
	qt422016.ReleaseByteBuffer(qb422016)
//line static.html:54
	return qs422016
//line static.html:54
}
