// This file is automatically generated by qtc from "thread.html".
// See https://github.com/valyala/quicktemplate for details.

//line thread.html:1
package templates

//line thread.html:1
import "strconv"

//line thread.html:2
import "github.com/bakape/meguca/lang"

//line thread.html:3
import "github.com/bakape/meguca/common"

//line thread.html:4
import "github.com/bakape/meguca/config"

//line thread.html:5
import "encoding/json"

//line thread.html:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line thread.html:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line thread.html:7
func streamrenderThread(qw422016 *qt422016.Writer, postHTML []byte, id uint64, board string, abbrev, locked bool, pos common.ModerationLevel) {
	//line thread.html:8
	conf := config.GetBoardConfigs(board)

	//line thread.html:9
	ln := lang.Get()

	//line thread.html:10
	if !locked {
		//line thread.html:10
		qw422016.N().S(`<form id="new-reply-form" action="/api/create-reply" method="post" enctype="multipart/form-data" class="top-margin hidden"><input name="board" type="text" value="`)
		//line thread.html:12
		qw422016.N().S(board)
		//line thread.html:12
		qw422016.N().S(`" hidden><input name="op" type="text" value="`)
		//line thread.html:13
		qw422016.N().S(strconv.FormatUint(id, 10))
		//line thread.html:13
		qw422016.N().S(`" hidden>`)
		//line thread.html:14
		streaminput(qw422016, sageSpec.wrap(), ln)
		//line thread.html:15
		streamnoscriptPostCreationFields(qw422016, pos)
		//line thread.html:16
		if !conf.TextOnly {
			//line thread.html:17
			streamuploadForm(qw422016)
			//line thread.html:18
		}
		//line thread.html:19
		streamcaptcha(qw422016, board)
		//line thread.html:20
		streamsubmit(qw422016, true)
		//line thread.html:20
		qw422016.N().S(`</form>`)
		//line thread.html:22
	}
	//line thread.html:22
	qw422016.N().S(`<span class="aside-container top-margin"><span class="act" id="top"><a href="#bottom">`)
	//line thread.html:26
	qw422016.N().S(ln.Common.UI["bottom"])
	//line thread.html:26
	qw422016.N().S(`</a></span><span class="act"><a href=".">`)
	//line thread.html:31
	qw422016.N().S(ln.Common.UI["return"])
	//line thread.html:31
	qw422016.N().S(`</a></span><span class="act"><a href="catalog">`)
	//line thread.html:36
	qw422016.N().S(ln.Common.UI["catalog"])
	//line thread.html:36
	qw422016.N().S(`</a></span><span id="expand-images" class="act noscript-hide"><a>`)
	//line thread.html:41
	qw422016.N().S(ln.Common.Posts["expandImages"])
	//line thread.html:41
	qw422016.N().S(`</a></span>`)
	//line thread.html:44
	streamhoverReveal(qw422016, "span", conf.Notice, ln.Common.UI["showNotice"])
	//line thread.html:45
	streamhoverReveal(qw422016, "span", conf.Rules, ln.Common.UI["rules"])
	//line thread.html:45
	qw422016.N().S(`</span><hr>`)
	//line thread.html:48
	qw422016.N().Z(postHTML)
	//line thread.html:48
	qw422016.N().S(`<div id="bottom-spacer"></div>`)
	//line thread.html:50
	if !locked {
		//line thread.html:50
		qw422016.N().S(`<aside class="act posting glass noscript-hide"><a>`)
		//line thread.html:53
		qw422016.N().S(ln.Common.UI["reply"])
		//line thread.html:53
		qw422016.N().S(`</a></aside>`)
		//line thread.html:56
	}
	//line thread.html:56
	qw422016.N().S(`<hr><span class="aside-container"><span class="act" id="bottom"><a href=".">`)
	//line thread.html:61
	qw422016.N().S(ln.Common.UI["return"])
	//line thread.html:61
	qw422016.N().S(`</a></span><span class="act"><a href="catalog">`)
	//line thread.html:66
	qw422016.N().S(ln.Common.UI["catalog"])
	//line thread.html:66
	qw422016.N().S(`</a></span><span class="act"><a href="#top">`)
	//line thread.html:71
	qw422016.N().S(ln.Common.UI["top"])
	//line thread.html:71
	qw422016.N().S(`</a></span>`)
	//line thread.html:74
	if !abbrev {
		//line thread.html:74
		qw422016.N().S(`<span class="act"><a href="?last=100#bottom">`)
		//line thread.html:77
		qw422016.N().S(ln.Common.UI["last"])
		//line thread.html:77
		qw422016.N().S(` `)
		//line thread.html:77
		qw422016.N().S(`100</a></span>`)
		//line thread.html:80
	}
	//line thread.html:80
	qw422016.N().S(`<span id="lock" style="visibility: hidden;">`)
	//line thread.html:82
	qw422016.N().S(ln.Common.UI["lockedToBottom"])
	//line thread.html:82
	qw422016.N().S(`</span></span>`)
	//line thread.html:85
	streamloadingImage(qw422016, board)
//line thread.html:86
}

//line thread.html:86
func writerenderThread(qq422016 qtio422016.Writer, postHTML []byte, id uint64, board string, abbrev, locked bool, pos common.ModerationLevel) {
	//line thread.html:86
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:86
	streamrenderThread(qw422016, postHTML, id, board, abbrev, locked, pos)
	//line thread.html:86
	qt422016.ReleaseWriter(qw422016)
//line thread.html:86
}

//line thread.html:86
func renderThread(postHTML []byte, id uint64, board string, abbrev, locked bool, pos common.ModerationLevel) string {
	//line thread.html:86
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:86
	writerenderThread(qb422016, postHTML, id, board, abbrev, locked, pos)
	//line thread.html:86
	qs422016 := string(qb422016.B)
	//line thread.html:86
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:86
	return qs422016
//line thread.html:86
}

// ThreadPosts renders the post content of a thread. Separate function to allow
// caching of generated posts.

//line thread.html:90
func StreamThreadPosts(qw422016 *qt422016.Writer, t common.Thread, json []byte) {
	//line thread.html:90
	qw422016.N().S(`<section id="thread-container" data-id="`)
	//line thread.html:91
	qw422016.N().S(strconv.FormatUint(t.ID, 10))
	//line thread.html:91
	qw422016.N().S(`">`)
	//line thread.html:92
	bls := extractBacklinks(1<<10, t)

	//line thread.html:93
	streamrenderThreadPosts(qw422016, t, bls, config.Get().RootURL, false)
	//line thread.html:93
	qw422016.N().S(`<script id="post-data" type="application/json">`)
	//line thread.html:95
	qw422016.N().Z(json)
	//line thread.html:95
	qw422016.N().S(`</script>`)
	//line thread.html:97
	streamencodeBacklinks(qw422016, bls)
	//line thread.html:97
	qw422016.N().S(`</section><script id="board-configs" type="application/json">`)
	//line thread.html:100
	qw422016.N().Z(config.GetBoardConfigs(t.Board).JSON)
	//line thread.html:100
	qw422016.N().S(`</script>`)
//line thread.html:102
}

//line thread.html:102
func WriteThreadPosts(qq422016 qtio422016.Writer, t common.Thread, json []byte) {
	//line thread.html:102
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:102
	StreamThreadPosts(qw422016, t, json)
	//line thread.html:102
	qt422016.ReleaseWriter(qw422016)
//line thread.html:102
}

//line thread.html:102
func ThreadPosts(t common.Thread, json []byte) string {
	//line thread.html:102
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:102
	WriteThreadPosts(qb422016, t, json)
	//line thread.html:102
	qs422016 := string(qb422016.B)
	//line thread.html:102
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:102
	return qs422016
//line thread.html:102
}

// Common functionality between index board pages and threads pages

//line thread.html:105
func streamrenderThreadPosts(qw422016 *qt422016.Writer, t common.Thread, bls backlinks, root string, index bool) {
	//line thread.html:106
	boardConfig := config.GetBoardConfigs(t.Board)

	//line thread.html:107
	c := articleContext{
		index:     index,
		sticky:    t.Sticky,
		locked:    t.Locked,
		rbText:    boardConfig.RbText,
		pyu:       boardConfig.Pyu,
		op:        t.ID,
		board:     t.Board,
		subject:   t.Subject,
		root:      root,
		backlinks: bls,
	}

	//line thread.html:119
	c.omit, c.imageOmit = CalculateOmit(t)

	//line thread.html:120
	streamrenderArticle(qw422016, t.Post, c)
	//line thread.html:122
	c.sticky = false

	//line thread.html:123
	c.locked = false

	//line thread.html:124
	c.omit, c.imageOmit = 0, 0

	//line thread.html:125
	c.subject = ""

	//line thread.html:126
	for _, p := range t.Posts {
		//line thread.html:127
		streamrenderArticle(qw422016, p, c)
		//line thread.html:128
	}
//line thread.html:129
}

//line thread.html:129
func writerenderThreadPosts(qq422016 qtio422016.Writer, t common.Thread, bls backlinks, root string, index bool) {
	//line thread.html:129
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:129
	streamrenderThreadPosts(qw422016, t, bls, root, index)
	//line thread.html:129
	qt422016.ReleaseWriter(qw422016)
//line thread.html:129
}

//line thread.html:129
func renderThreadPosts(t common.Thread, bls backlinks, root string, index bool) string {
	//line thread.html:129
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:129
	writerenderThreadPosts(qb422016, t, bls, root, index)
	//line thread.html:129
	qs422016 := string(qb422016.B)
	//line thread.html:129
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:129
	return qs422016
//line thread.html:129
}

//line thread.html:131
func streamencodeBacklinks(qw422016 *qt422016.Writer, bls backlinks) {
	//line thread.html:131
	qw422016.N().S(`<script id="backlink-data" type="application/json">`)
	//line thread.html:133
	buf, _ := json.Marshal(bls)

	//line thread.html:134
	qw422016.N().Z(buf)
	//line thread.html:134
	qw422016.N().S(`</script>`)
//line thread.html:136
}

//line thread.html:136
func writeencodeBacklinks(qq422016 qtio422016.Writer, bls backlinks) {
	//line thread.html:136
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:136
	streamencodeBacklinks(qw422016, bls)
	//line thread.html:136
	qt422016.ReleaseWriter(qw422016)
//line thread.html:136
}

//line thread.html:136
func encodeBacklinks(bls backlinks) string {
	//line thread.html:136
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:136
	writeencodeBacklinks(qb422016, bls)
	//line thread.html:136
	qs422016 := string(qb422016.B)
	//line thread.html:136
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:136
	return qs422016
//line thread.html:136
}
