// This file is automatically generated by qtc from "thread.html".
// See https://github.com/valyala/quicktemplate for details.

//line thread.html:1
package templates

//line thread.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line thread.html:1
import "github.com/bakape/meguca/lang"

//line thread.html:2
import "github.com/bakape/meguca/common"

//line thread.html:3
import "github.com/bakape/meguca/config"

//line thread.html:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line thread.html:5
func streamrenderThread(qw422016 *qt422016.Writer, postHTML []byte, ln lang.Pack) {
	//line thread.html:5
	qw422016.N().S(`<span class="aside-container top-margin"><span class="act" id="top"><a href="#bottom">`)
	//line thread.html:9
	qw422016.N().S(ln.UI["bottom"])
	//line thread.html:9
	qw422016.N().S(`</a></span><span id="expand-images" class="act"><a>`)
	//line thread.html:14
	qw422016.N().S(ln.Common.Posts["expandImages"])
	//line thread.html:14
	qw422016.N().S(`</a></span></span><noscript>TODO: Noscript post creation</noscript><hr>`)
	//line thread.html:22
	qw422016.N().Z(postHTML)
	//line thread.html:22
	qw422016.N().S(`<div id="bottom-spacer"></div><aside class="act posting glass"><a>`)
	//line thread.html:26
	qw422016.N().S(ln.UI["reply"])
	//line thread.html:26
	qw422016.N().S(`</a></aside><hr><span class="aside-container"><span class="act" id="bottom"><a href="." class="history">`)
	//line thread.html:33
	qw422016.N().S(ln.UI["return"])
	//line thread.html:33
	qw422016.N().S(`</a></span><span class="act"><a href="#top">`)
	//line thread.html:38
	qw422016.N().S(ln.UI["top"])
	//line thread.html:38
	qw422016.N().S(`</a></span><span class="act"><a href="?last=100" class="history reload">`)
	//line thread.html:43
	qw422016.N().S(ln.Common.UI["last"])
	//line thread.html:43
	qw422016.N().S(` `)
	//line thread.html:43
	qw422016.N().S(`100</a></span><span id="lock" style="visibilty: hidden;">`)
	//line thread.html:47
	qw422016.N().S(ln.UI["lockedToBottom"])
	//line thread.html:47
	qw422016.N().S(`</span></span>`)
//line thread.html:50
}

//line thread.html:50
func writerenderThread(qq422016 qtio422016.Writer, postHTML []byte, ln lang.Pack) {
	//line thread.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:50
	streamrenderThread(qw422016, postHTML, ln)
	//line thread.html:50
	qt422016.ReleaseWriter(qw422016)
//line thread.html:50
}

//line thread.html:50
func renderThread(postHTML []byte, ln lang.Pack) string {
	//line thread.html:50
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:50
	writerenderThread(qb422016, postHTML, ln)
	//line thread.html:50
	qs422016 := string(qb422016.B)
	//line thread.html:50
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:50
	return qs422016
//line thread.html:50
}

// ThreadPosts renders the post content of a thread. Separate function to allow
// caching of generated posts.

//line thread.html:54
func StreamThreadPosts(qw422016 *qt422016.Writer, t common.Thread, json []byte, omit, imageOmit int) {
	//line thread.html:54
	qw422016.N().S(`<div id="thread-container">`)
	//line thread.html:56
	root := config.Get().RootURL

	//line thread.html:57
	streamrenderArticle(qw422016, t.Post, t.ID, omit, imageOmit, t.Subject, root)
	//line thread.html:58
	for _, p := range t.Posts {
		//line thread.html:59
		streamrenderArticle(qw422016, p, t.ID, 0, 0, "", root)
		//line thread.html:60
	}
	//line thread.html:60
	qw422016.N().S(`</div><script id="post-data" type="application/json">`)
	//line thread.html:63
	qw422016.N().Z(json)
	//line thread.html:63
	qw422016.N().S(`</script><script id="board-configs" type="application/json">`)
	//line thread.html:66
	qw422016.N().Z(config.GetBoardConfigs(t.Board).JSON)
	//line thread.html:66
	qw422016.N().S(`</script>`)
//line thread.html:68
}

//line thread.html:68
func WriteThreadPosts(qq422016 qtio422016.Writer, t common.Thread, json []byte, omit, imageOmit int) {
	//line thread.html:68
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line thread.html:68
	StreamThreadPosts(qw422016, t, json, omit, imageOmit)
	//line thread.html:68
	qt422016.ReleaseWriter(qw422016)
//line thread.html:68
}

//line thread.html:68
func ThreadPosts(t common.Thread, json []byte, omit, imageOmit int) string {
	//line thread.html:68
	qb422016 := qt422016.AcquireByteBuffer()
	//line thread.html:68
	WriteThreadPosts(qb422016, t, json, omit, imageOmit)
	//line thread.html:68
	qs422016 := string(qb422016.B)
	//line thread.html:68
	qt422016.ReleaseByteBuffer(qb422016)
	//line thread.html:68
	return qs422016
//line thread.html:68
}
